### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by HmHmmHm** [organization/ParfaitAuth#1]
- [x] TODO 식별번호는 찾는순서대로 9999까지 발급하고, 9999초과시 1부터 다시 시작하게..
- [x] serverUUID
  -updated: -141410403
  -index: ~~
  -push-1: 0
- [x] TODO 타서버에 유저가 있을때 문제가 되는 명령어는 일단 멈추고 노티피케이션처리
- [x] TODO 계정정보얻기->접속서버다를경우->해당서버살아있다면->명령어정지후->내보내기기능작동->다시작동
- [x] TODO 타서버에 명령수행하게하는 노티피케이션 컬렉션 추가
- [x] TODO 타서버에 있는 유저를 대상으로 명령어가 발동될 경우
  일단 무조건적으로 해당 노티피케이션 기능으로 내보내게 하도록 처리
- [x] TODO Notification
- [x] TODO 영향받는 대상
  AccountTypeCommand /계정 유형
  AccountForceLoginCommand /계정 접속
  AccountDeleteCommand /계정 삭제
  (BanAccountCommand) /b
  (BanIpAddressCommand) /i
  (BanSubnetAddressCommand) /s
- [x] TODO 이벤트생성
  ChangeNickEvent
  ChangePasswordEvent
  RegisterEvent
  UnregisterEvent
  LoginEvent
  LogoutEvent

NotificationSendEvent
NotificationReceiveEvent
BanAccountEvent
BanIpAddressEvent
BanSubnetAddressEvent
BanReleaseEvent
- [x] 아래 메시지들 메시지파일에 내장

/인증 - 인증에 필요한 인증용 명령어를 표시합니다.
/인증 안내 - 서버 인증체계에 대한 설명을 표시합니다.

/계정관리 - 계정관리에 필요한 관리용 명령어를 표시합니다.
/밴처리 - 차단처리에 필요한 밴처리 명령어를 표시합니다.

/계정관리 - 계정관리에 필요한 관리용 명령어를 표시합니다.
/계정 유형 <아이디> <유형지정>
/계정 접속 <아이디>
/계정 삭제 <아이디>
/계정 통계

/계정 유형 /account type AccountTypeCommand
/계정 접속 /account login AccountForceLoginCommand
/계정 삭제 /account del AccountDeleteCommand
/계정 통계 /account stat AccountStatisticsCommand

/밴처리 - 밴처리에 필요한 밴처리 명령어를 표시합니다.
명령어: /a /f /b /i /s /r
(약어: account find ban ip subnet release)
(번역: 계정검색 검색 계정밴 아이피밴 서브넷밴 밴해제)
(식별번호는 @숫자 와 같이 적습니다!)

/밴처리 /howtoban (HowToBanCommand)
/a (AccountInfoCommand)
/f (AccountFindCommand)
/b (BanAccountCommand)
/i (BanIpAddressCommand)
/s (BanSubnetAddressCommand)
/r (BanReleaseCommand)

/a <필터> <검색어>
밴처리를 위해 해당 유저의 계정정보를 찾습니다.
(사용가능필터, 아이디, 닉네임, 식별번호)
(아이디 혹은 닉네임을 정확하게 입력해야합니다.)

/f <필터> <검색어>
밴처리를 위해 지정된 유저 식별번호를 찾습니다.
(사용가능필터: 아이디, 닉네임, 채팅, 나감, 접속, 복잡닉)

/b <식별번호|아이디> <기간> <사유>
해당 유저의 계정을 차단합니다.
(기간에 숫자만 입력시 분단위가 되며)
(앞에 h, d를 붙일 수 있고, 각각 시간,일자단위)
(사유는 반드시 적어야하며 띄어쓰기가 가능함)

/i <식별번호|아이피> <기간> <사유>
해당 아이피 혹은 유저의 아이피를 차단합니다.
(기간에 숫자만 입력시 분단위가 되며)
(앞에 h, d를 붙일 수 있고, 각각 시간,일자단위)
(사유는 반드시 적어야하며 띄어쓰기가 가능함)

/s <식별번호|서브넷> <기간> <사유>
해당 서브넷 혹은 유저의 서브넷을 차단합니다.
(기간에 숫자만 입력시 분단위가 되며)
(앞에 h, d를 붙일 수 있고, 각각 시간,일자단위)
(사유는 반드시 적어야하며 띄어쓰기가 가능함)

/r <필터> <검색어> <사유>
해당 유저의 계정정보를 찾고 차단을 해제합니다.
(사용가능필터, 아이디, 닉네임, 식별번호, 아이피, 서브넷)
(검색어를 정확하게 입력해야합니다.)
