### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by HmHmmHm** [organization/ParfaitAuth#2]
- [x] args[0] != null
  이거 전부 args.length == 0 이런식으로 변경해야함
- [x] this.commandName + 쓴거 모두 변경해야함
  this.commandKey 로
- [x] 리피팅되는 테스크는 테스크핸들러 추가해야함
  // /인증 을 입력한 경우 인증용 명령어 전송
  SendMessageTask task = new SendMessageTask(sender, this.commandKey + "-sub-info-help-");
  TaskHandler handler = this.getServer().getScheduler().scheduleRepeatingTask(task, 40);
  task.setHandler(handler);
- [x] 스트링을 == 로 따지면 안맞음.... equal로 체크 하게 모두변경해야함
- [x] 회원탈퇴 계정이름 변경시 한번씩 물어보기
- [x] ChangedNameEvent 추가
- [x] A기기에서 쓰던 계정을 B계정에서 쓰면 어떻게되는가? 링크처리? 해야함
  ->임시 UUUID계정이 삭제되고 이전ID계정에 UUID가 갱신됨
- [x] 게임모드변경권한주기
- [x] 차단된 네트워크주소일경우 해당접근차단
- [x] 차단된 유저일경우 해당접근차단
- [x] 전면적체크 콘솔에서 명령어 실행가능한지
- [x] 모든 테스크에 try catch 적용해야하는지 체크
- [x] 게임모드 정상적용되는지 체크 및 모든 명령어 작동체크
- [x] 파르페오스 명령어 퍼미션 갖고 있는지 매 선두에 체크
- [x] 파르페오스가 작동중 인터넷이 끊기면 유저계정정보 파일로 백업한 후 온라인상태가되면 업로드하도록 처리. -> 분단위로 업로드 처리하도록하게함, 해당서버가 죽은사이 다른서버에서 정상활동할 수도 있으니 별도로 데이터 처리는 하지않음
- [x] 빌더가 /gamemode 명령어로 타인의 게임모드를 바꿀 수는 없게 처리
- [x] 내부값 보기위해 심었던 System.out.println 싹지우기
- [x] unauthorized.dat 파일이 새로열린 *E~l.dat 파일에 영향을 주지 않음 교정해야할지도->이전에 이용되던 로컬내 NBT파일저장체계 무시, 해당 파일들 생성은 기본로직이 막진 못하고, 그냥 매순간마다 비동기 삭제처리
- [x] 계정명 전부 아이디로
- [x] 안내메시지가 나오는 동안엔 채팅 안보내게? 색상코드때고 *가 앞에 붙은것만?
- [x] 유저나갈때나 서버꺼질때 계정정보 업로드잘되고 있는지 체크
